FROM golang:1.25.3-alpine AS builder

WORKDIR /app

RUN go env -w GOPROXY=https://goproxy.io,direct

COPY ./go.mod ./go.sum ./

RUN go mod download -x

COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-w -s " -o main ./cmd/server/main.go

FROM alpine:3.21

WORKDIR /app

RUN mkdir -p ./internal/jwt

COPY ./internal/jwt/private_key.pem ./internal/jwt/
COPY ./internal/jwt/public_key.pem ./internal/jwt/

COPY --from=builder /app/main .


EXPOSE 8080

CMD ["./main"]