// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/niflheimdevs/smartparking/internal/config"
	"github.com/niflheimdevs/smartparking/internal/db"
	"github.com/niflheimdevs/smartparking/internal/delivery/http"
	"github.com/niflheimdevs/smartparking/internal/delivery/http/handler"
	"github.com/niflheimdevs/smartparking/internal/repository"
	"github.com/niflheimdevs/smartparking/internal/usecase"
)

// Injectors from wire.go:

func InitializeApp() (*http.App, error) {
	configConfig := config.Load()
	gormDB := db.Connect(configConfig)
	vehicleRepository := repository.NewVehicleRepository(gormDB)
	vehicleUseCase := usecase.NewVehicleUseCase(vehicleRepository)
	vehicleHandler := handler.NewVehicleHandler(vehicleUseCase)
	app := http.NewApp(configConfig, gormDB, vehicleHandler)
	return app, nil
}
